name: Lint, Build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make lint
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15.10'
    - name: Run unit tests
      run: make test
